// Represents a single extracted action item
export interface ActionItem {
  id?: string;            // Auto-generated by Supabase (UUID)
  meeting_id?: string;    // Links to parent meeting
  task: string;           // "Send feedback to agency by Wednesday"
  owner: string;          // "Mark"
  deadline: string;       // "Wednesday" or "2026-03-18"
  priority: 'high' | 'medium' | 'low';
  status: 'pending' | 'in_progress' | 'completed';
  created_at?: string;    // Auto-set by Supabase
}

// Represents a meeting with its transcript and extracted items
export interface Meeting {
  id?: string;
  title: string;          // "Team Sync — March 15"
  raw_transcript: string; // The full pasted transcript
  summary?: string;       // AI-generated 2-3 sentence summary
  created_at?: string;
  action_items?: ActionItem[];  // Nested when we query with joins
}

// The shape of what OpenAI returns
export interface ExtractionResponse {
  summary: string;
  action_items: ActionItem[];
}
